// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: url.sql

package repository

import (
	"context"
	"time"
)

const createURL = `-- name: CreateURL :exec
INSERT INTO urls (
    original_url,
    short_code,
    expires_at,
    is_custom
) VALUES (
             ?, ?, ?, ?
         )
`

type CreateURLParams struct {
	OriginalUrl string    `json:"original_url"`
	ShortCode   string    `json:"short_code"`
	ExpiresAt   time.Time `json:"expires_at"`
	IsCustom    bool      `json:"is_custom"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) error {
	_, err := q.db.ExecContext(ctx, createURL,
		arg.OriginalUrl,
		arg.ShortCode,
		arg.ExpiresAt,
		arg.IsCustom,
	)
	return err
}

const deleteExpiredURLs = `-- name: DeleteExpiredURLs :exec
DELETE FROM urls
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredURLs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredURLs)
	return err
}

const getCreatedURL = `-- name: GetCreatedURL :one
SELECT id, original_url, short_code, created_at, expires_at, is_custom FROM urls
WHERE id = LAST_INSERT_ID()
`

func (q *Queries) GetCreatedURL(ctx context.Context) (Url, error) {
	row := q.db.QueryRowContext(ctx, getCreatedURL)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsCustom,
	)
	return i, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, original_url, short_code, created_at, expires_at, is_custom FROM urls
WHERE short_code = ? AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsCustom,
	)
	return i, err
}

const isShortCodeAvailable = `-- name: IsShortCodeAvailable :one
SELECT NOT EXISTS (
    SELECT 1 FROM urls
    WHERE short_code = ?
) AS is_available
`

func (q *Queries) IsShortCodeAvailable(ctx context.Context, shortCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isShortCodeAvailable, shortCode)
	var is_available bool
	err := row.Scan(&is_available)
	return is_available, err
}
